title: the tippens terminal
author: tippens 
email: solarsnake88@proton.me 
description: >-
  Welcome to my personal website and blog, presented in a retro terminal style.
baseurl: ""
url: "https://solarsnake.github.io" 
github_username: solarsnake 

theme: minima 
plugins:
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  pages:
    output: true
    permalink: /:name/ # This ensures pages/resume.md becomes /resume/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/