baseURL = "https://solarsnake.github.io/" # Corrected baseURL
languageCode = "en-us"
title = "Just The Tipp"

# Remove the theme line if you have your baseof.html in your project's layouts/_default/
# theme = "terminal"

[params]
  description = "DevOps Cloud Engineer. Specializing in AI and Matrix-like efficiency."
  # email = "your.email@example.com" # Replace with your actual email
  # linkedin = "yourlinkedinprofile" # Replace
  # github = "solarsnake" # Your GitHub username

# Ensure HTML is the primary output for the homepage
[outputs]
  home = ["HTML", "RSS"] # Make sure HTML is listed (it's usually default)