baseURL = "https://solarsnake.github.io/"
languageCode = "en-us"
title = "SolarSnake :: Terminal" # You can change this site title

[params]
  description = "DevOps Cloud Engineer Portfolio. Type 'help' for commands."
  author = "SolarSnake"

# This ensures Hugo generates HTML and an RSS feed for the homepage.
# And just HTML for regular pages. It's often default but good to be explicit.
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

# By not specifying a 'theme' here, Hugo will use the layouts in your project's /layouts directory.