name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby, Bundler, and Jekyll
        uses: ruby/setup-ruby@v1 
        with:
          ruby-version: '3.1'
          bundler-cache: true 

      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 